name: noteapp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  adaptive_dialog: ^2.0.0
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  drift: ^2.14.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.6
  go_router: ^13.0.1
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  path: 1.8.3
  path_provider: ^2.1.2
  sqlite3_flutter_libs: ^0.5.18

dev_dependencies:
  build_runner: ^2.4.7
  drift_dev: ^2.14.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
